### ISSUE TITLE
onDisconnect()

### ISSUE THREAD

**Issue by verymilan** [Steltie/purrim#1]
Hi, just wanna say i am looking forward for you project because i am hoping for some cool desktop client for jabber in the future.

Sadly i cannot test it because `onDisconnect()` is all i get after open the binary... .

**Comment by binaryDiv** [comment]
To be honest, I'm really really confused right now that someone actually found this project... It's kind of abandoned though, due to my lack of time and motivation to continue working on it. :(
I think I will restart this project one day, hopefully in the near future. If you want, I can inform you about that. :)

**Comment by verymilan** [comment]
Hmm sounds sad. I think that jabber really need modern, good looking and good working clients like conversations, unlike gajim where httpsupload crashes the whole application if the image is too big and much other (very old) issues. :/

Maybe it helps you to create a fancy project site and cool screenshots/mockups.
For example. I will watch your project so you dont must inform me, exept you'll move to gitlab for example.^^

The projectname is a good start btw :+1: 
Regards
